### ISSUE TITLE
Bug: 调用sendcmd_with_resp时参数数量错误

### ISSUE THREAD

**Issue by chfwd** [ToolDelta/ToolDelta#169]
### 操作系统

Windows

### ToolDelta 版本

0.7.11(54ba378)

### 描述问题

```
[13:24:06]  报错  ToolDelta 运行过程中出现问题：Traceback (most recent call last):
[13:24:06]  报错    File "d:\git\ToolDelta\tooldelta\starter.py", line 37, in start_tool_delta
[13:24:06]  报错      raise tooldelta.launcher.launch()
[13:24:06]  报错    File "d:\git\ToolDelta\tooldelta\launch_cli.py", line 612, in launch
[13:24:06]  报错      self._launcher_listener()
[13:24:06]  报错    File "d:\git\ToolDelta\tooldelta\frame.py", line 768, in Inject
[13:24:06]  报错      self.tmp_tp_all_players()
[13:24:06]  报错    File "d:\git\ToolDelta\tooldelta\frame.py", line 894, in tmp_tp_all_players
[13:24:06]  报错      BotPos: tuple[float, float, float] = getPosXYZ(self.bot_name)
[13:24:06]  报错    File "d:\git\ToolDelta\tooldelta\game_utils.py", line 159, in getPosXYZ
[13:24:06]  报错      res = getPos(player, timeout=timeout)["position"]
[13:24:06]  报错    File "d:\git\ToolDelta\tooldelta\game_utils.py", line 84, in getPos
[13:24:06]  报错      result = game_ctrl.sendcmd_with_resp(f'/querytarget @a[name="{target}"]', timeout)
[13:24:06]  报错    File "d:\git\ToolDelta\tooldelta\frame.py", line 829, in sendcmd_with_resp
[13:24:06]  报错      resp: Packet_CommandOutput = self.sendcmd_with_resp(cmd, True, timeout)  # type: ignore
[13:24:06]  报错  TypeError: GameCtrl.sendcmd_with_resp() takes from 2 to 3 positional arguments but 4 were given
[13:24:06]  报错 
``` 

### 复现步骤

1.拉取最新代码
2.下载依赖库并运行
3.产生问题

**Comment by Happy2018new** [comment]
Confirmed.

**Comment by SuperScript-PRC** [comment]
严重 bug，语法问题。将会在 7/8/2024修复且更新最新版本。

**Comment by SuperScript-PRC** [comment]
Fix: (0885c2)[https://github.com/ToolDelta/ToolDelta/commit/958dbc516918a26e0ec88fc88da1d52d560885c2]

**Comment by Happy2018new** [comment]
You can not call function `sendcmd_with_resp` again and again.

**Comment by Happy2018new** [comment]
![image](https://github.com/ToolDelta/ToolDelta/assets/109064184/31372b27-49f8-4f22-b243-ca333178f2cc)

**Comment by SuperScript-PRC** [comment]
wait a moment
what's vscode did??

**Comment by Happy2018new** [comment]
![image](https://github.com/ToolDelta/ToolDelta/assets/109064184/1c0a597f-a2b4-42d9-9f80-7f625afcf4a0)

**Comment by Happy2018new** [comment]
But that's ture, someone write these codes...

**Comment by SuperScript-PRC** [comment]
Fix again: [bfe742](https://github.com/ToolDelta/ToolDelta/commit/a398f6d9783d8fde5a01541a0a619ccb80bfe742)

**Comment by SuperScript-PRC** [comment]
@Happy2018new test it plz and ill bump ~0.7.13

**Comment by Happy2018new** [comment]
![image](https://github.com/ToolDelta/ToolDelta/assets/109064184/82c48487-3c11-4f31-a034-580eb2c6162e)

**Comment by Happy2018new** [comment]
Everything seems work as expected, maybe bug is fixed.

**Comment by SuperScript-PRC** [comment]
alright lets bump now

**Comment by Happy2018new** [comment]
But I have a problem.

**Comment by Happy2018new** [comment]
![image](https://github.com/ToolDelta/ToolDelta/assets/109064184/760182f1-d7fa-4c64-acaf-a1d08c45db8d)

**Comment by Happy2018new** [comment]
See the image, you can see someone use `True` as timeout value but not 1, why use bool?

**Comment by SuperScript-PRC** [comment]
function referrence not update.

**Comment by Happy2018new** [comment]
OK, hope all the bug related this issue was fixed, or other collaborator will get some many emails.

After you bump version, please closed this issue as completed.

**Comment by Happy2018new** [comment]
Emmm, yes.
